version: "3.8"

services:
  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=chat_db
      - MYSQL_USER=krunal
      - MYSQL_PASSWORD=test_123
      - MYSQL_ROOT_PASSWORD=test_123

  express:
    build: ./backend
    restart: always
    ports:
      - "3010:3010"
    depends_on:
      - database
    environment:
      DATABASE_HOST: database

  react:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - express
    environment:
      VITE_API_URL: http://localhost:3010 # Use the hostname and port of the express container
